# we specify the version of docker compose
version: "3.8"
services: #services are projects that we want images and container for
  api: #it doesnt have to be the same name with the folder
    build: ./api #we say docker compose to build the image inside api folder
    container_name: api_c
    ports: #port mapping
      - "4000:4000"
    volumes:
      - ./api:/app
      - /app/node_modules
  frontend:
    build: ./myblog
    container_name: reactapp_c
    ports: #port mapping
      - "3000:3000"
    # volumes: doestn work on windows
    #   - ./myblog:/app
    #   - /app/node_modules
    stdin_open: true # starts the container in interactive mode
    tty: true
